parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '9.6'
        charset: utf8mb4

        host:     '%env(DB_HOST)%'
        port:     5432
        dbname:   '%env(DB_NAME)%'
        user:     '%env(DB_USER)%'
        password: '%env(DB_PASS)%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model'
                prefix: 'App\Model'
                alias: App
